using UnityEngine;
using NaughtyAttributes;

namespace FletcherLibraries
{
    /// <summary>
    /// Parent class for Scriptable Objects that represent static data, allowing them to be referenced by their ID.
    /// </summary>
    public abstract class StaticDataObject : ScriptableObject
    {
        [Tooltip("Unique indentifier generated by data compilation process")]
        [ReadOnly][SerializeField] protected int _id = -1;
        
        /// <summary>
        /// A unique identifier for this Static Data object, that can be used to refer to the object when passing data through a network or reading save data from disk, for instance
        /// </summary>
        public int ID
        {
            get => _id;
#if UNITY_EDITOR
            set => _id = value; //NOTE: The setter should only be used internally by data compilation tools in the editor.
#endif
        }
    }
}
